name: Workflow for Node using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities in dependencies
        uses: snyk/actions/node@master # See https://github.com/snyk/actions for other supported build tools/languages
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test --all-projects --json-file-output=snyk_dependencies.json
      - name: Run Snyk to check for vulnerabilities in code
        uses: snyk/actions/node@master # See https://github.com/snyk/actions for other supported build tools/languages
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test --all-projects --json-file-output=snyk_code.json
      - name: Add Job Summary from Snyk reports
        uses: medly/snyk-job-summary-action@v1
        with:
            dependencies-report-path: snyk_dependencies.json # The file name of json file which is generated on snyk test
            code-report-path: snyk_code.json # The file name of json file which is generated on snyk code test
